### ISSUE TITLE
(김예리나) 겜프프로젝트 과정평가용(방문기록)

### ISSUE THREAD

**Issue by GGMinwok** [SHOOTTHEMALL/Making-Graduation-L.B.M#1]
6/2 저장소 접속 처리됨

**Comment by GGMinwok** [comment]
6/8 작업내용 - 지금까지 한 것, 오늘 1-3교시에 한 것 구분해서 과정 기록 해주기!

**Comment by SHOOTTHEMALL** [comment]
엘범 넘기기 기능 완료
미니게임 룰렛돌리기 개발중, 다음시간까지 완료할 예정

**Comment by GGMinwok** [comment]
6/9- 6/8까지의 commit/comment 확인함.

**Comment by SHOOTTHEMALL** [comment]
룰렛 미니게임 개발, 결과 부분에서 버그가 있다.
앞으로는 룰렛 결과 부분의 버그와 투박한 이미지를 채울 것이다.

**Comment by GGMinwok** [comment]
6/22 지난주작업확인함

**Comment by GGMinwok** [comment]
6/30 확인함
고생했어요~^^
마지막 확인완료
작업과정 기록 남겨두세요. 
(2022년 동안 삭제 금지)
